[profile.default]
src = 'src'
out = 'out'
libs = ['lib']



# Correct remapping syntax
remappings = ["@chainlink/=lib/chainlink-brownie-contracts/"]


# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

[rpc_endpoints]
sepolia = "https://eth-sepolia.g.alchemy.com/v2/F6MChirlnYeBedE0CS7_D8YnOghZPLw7"